InstallCmd = apt-get install -y
RemoveCmd  = apt-get --purge remove -y
InfoCmd    = dpkg -s

KeeperFile = /var/lib/debfoster/keepers

UseEssential = yes
UseHold = yes
UsePreDepends = yes

UseRecommends = no
UseSuggests = no
UseTasks = no

MaxPriority = standard

NegativeKeepers = yes

GuessDepends = doc,dev,dbg

KeepSections =
NokeepSections =

Verbose = yes
Quiet = no
Force = no